// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/linuxxiaoyu/Go-000/Week04/pkg/app"
)

// Injectors from wire.go:

func InitializeApp(port2 string) *app.App {
	appApp := NewServer(port2)
	return appApp
}
